### ISSUE TITLE
webui "forgets" user's affiliate code if he navigates to the token presale page via an URL that contains any affiliate code

### ISSUE THREAD

**Issue by al-maisan** [verity-team/dws#176]
Here's my affiliate code:

![image](https://github.com/verity-team/dws/assets/367773/fa79caeb-a0ec-4c1f-9498-629935e96451)

when I use an URL  with another user's referral code to go to the presale page the webapp has "forgotten" my _own_ affiliate code 

![image](https://github.com/verity-team/dws/assets/367773/0d93ac1c-b538-47c4-a3f5-e5384eff05f7)

**Comment by al-maisan** [comment]
related to issue #175 ??

**Comment by al-maisan** [comment]
This happens even if I use my own referral link (https://truthmemes.io:8086/?afc=2117ddddf233f5eb)

**Comment by alfydev** [comment]
I observe this as well. It happens with the "Share Now" link when an affiliate code is being provided as argument.
However: you can still click on "Generate affiliate code" button, sign again with MetaMask, and it will then show your correct affiliate code, i.e. it will *not* generate a new one.

It would be nice if pages with an affiliate code argument would remember one's own affiliate code when clicking on Share Now (instead of having to re-sign again). It is a minor issue however, since this doesn't cause one wallet to have multiple affiliate codes in the DB.
